version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: tb-postgres
    restart: always
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  thingsboard:
    image: thingsboard/tb-postgres:3.9.1
    container_name: thingsboard
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:9090"
      - "1883:1883"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard

volumes:
  tb-postgres-data:
  tb-data:
  tb-logs: